### ISSUE TITLE
mapbox.addImage() doesn't work from locale storage

### ISSUE THREAD

**Issue by mariuszskoczylas** [EddyVerbruggen/nativescript-mapbox#410]
Loading image from  from res:// or even from any other directory from projects sources works, but it failed when path point to local storage. Im using clustering points and want to load images from backend and then using "icon-image" in symbol feature to point to this image added by mapbox.addImage(), due there is no other way to add image ( adding custom marker is not a solution, or someone know how to create clustered custom markers, url to image looks like is not supported ). For me looks like there is no other way to add custom icons not predefined before application release in case of clustering option.

**Comment by Yermo** [comment]
I'm no longer maintaining this project as I've moved away from Nativescript. Please refer to this project: https://github.com/nativescript-community/ui-mapbox
